name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [lts/*, lts/-1]

    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
